name: 'Tag'

description: |
  Tags the repository with the next highest patch number given an existing tag.

outputs:
  tag:
    description: 'Tag produced from the action'

runs:
  using: 'docker'
  image: 'Dockerfile'
