name: 'Update Dependency from Repository Dispatch'

description: |
  This action updates the buildpack.toml with a new dependency version.
  Specifically, when it receives a repository_dispatch event with event type
  "dependency-update", it updates that dependency in preparation for a commit.

runs:
  using: 'docker'
  image: 'Dockerfile'
